### ISSUE TITLE
Use V shortcut to Vote

### ISSUE THREAD

**Issue by oebe** [tatablack/leaner-coffee-powerup#37]
It would be nice if you could use the `V` shortcut to vote on a card, similar to Trellos Voting Power-Up.

**Comment by tatablack** [comment]
I agree 🙂 I vaguely remember trying this and seeing that it wasn't possible (the Voting Power-up is "special"), but I'll dig my old code and get back to you - even if it's just to confirm it's not doable.

**Comment by tatablack** [comment]
I can confirm that, unfortunately, it's not yet possible.
However, Trello may support it in the future - see [this conversation](https://community.developer.atlassian.com/t/power-up-api-for-keyboard-shortcuts/36057) for more details. I'll reopen the ticket if it happens.
