### ISSUE TITLE
Ability to remove discussion time from card

### ISSUE THREAD

**Issue by gitpauld** [tatablack/leaner-coffee-powerup#38]
I started a discussion on accident and it seems to only way to remove or undo added discussion time to a card is to archive the card and remake it. I'm hoping there's a better way because that's pretty obnoxious.

**Comment by tatablack** [comment]
Hi, @gitpauld, thanks for the feedback.
There's currently no way to reset the discussion timer, but it sounds like a sensible feature request.

I'm thinking an additional item in the "Discussion" menu, with a label like "Reset discussion time" or similar, should satisfy your requirement. What do you think?

Disclaimer: I haven't been working on this power-up for a while, so I'm not sure _when_ I'll be able to tackle this, but my intent is still to keep working on it when I can 🤞 .

**Comment by gitpauld** [comment]
Thank you for responding with your thoughts! Since you responded directly & so quickly, I want to also let you know how much the company I work for appreciates your Trello power-up. In specific, everyone who has been part of Lean Coffee love the voting feature and how that has been put together with the ability to sort and remove votes. 

For this issue, your suggestion of having a “reset discussion time” button would satisfy things. 

After writing about the issue, I noticed a few of the other pending feature requests here on Github would also be potentially useful. Particularly the ones to set the discussion timer to count-down in any per minute increment. (Our discussions are usually 8 minutes then vote for an 4 additional minutes.)
