### ISSUE TITLE
Possibility to reset timer

### ISSUE THREAD

**Issue by vannie01** [tatablack/leaner-coffee-powerup#41]
When timer was started accidentally, there is no way to reset it, other then creating the card again on the board and remove the old one.

**Comment by tatablack** [comment]
Hi 😌 You'll be glad to hear this has been asked before (#38) and already implemented (#39).
It hasn't been released yet, though. When it is (I haven't planned next release yet), you should see it in your boards.

Thanks again for the feedback 👍🏻
