### ISSUE TITLE
Adding a shortcut to vote

### ISSUE THREAD

**Issue by amandavarella** [tatablack/leaner-coffee-powerup#55]
On the original trello voting power up, you can vote in a card by pressing the key `v` while hovering, or inside a card.
It would be handy to have the same option on the Leaner Coffee power up.

Thank you

**Comment by tatablack** [comment]
Hi, Amanda.
Unfortunately, that's not technically possible (yet). It's been asked before (see #37 and #40), so you're not alone in wishing this functionality were available.

I bumped [this old thread](https://community.developer.atlassian.com/t/power-up-api-for-keyboard-shortcuts/36057) in Trello's community forums; I'll wait a few more days to see whether anyone from Atlassian gives us an update.

**Comment by tatablack** [comment]
Alas, it appears it's still not gonna be possible, and won't be for a while. 😕 
(screenshots from the community forums, link in the previous post)

<img width="801" alt="Screenshot 2022-03-29 at 01 37 20" src="https://user-images.githubusercontent.com/1095044/160504480-fda77c2c-405d-4d39-bdd2-08badfc74113.png">
